pal_motors_controller:
  type: "joint_group_position_controller/JointGroupPositionController"
  joints:
    - torso_1_joint
    - torso_2_joint
    - head_1_joint
    - head_2_joint
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint

  gains:
    torso_1_joint:                  {p: 1500.0, d: 800.0, i: 30, i_clamp: 6.0}
    torso_2_joint:                  {p: 1500.0, d: 800.0, i: 30, i_clamp: 6.0}
    head_1_joint:                   {p: 300, d: 250, i: 10, i_clamp: 1.5}
    head_2_joint:                   {p: 300, d: 250, i: 10, i_clamp: 1.5}
    arm_right_1_joint: &arm_1_gains {p: 800, d: 500, i: 20, i_clamp: 3.0}
    arm_right_2_joint: &arm_2_gains {p: 800, d: 500, i: 20, i_clamp: 3.0}
    arm_right_3_joint: &arm_3_gains {p: 600, d: 350, i: 15, i_clamp: 2.0}
    arm_right_4_joint: &arm_4_gains {p: 800, d: 500, i: 20, i_clamp: 3.0}
    arm_right_5_joint: &arm_5_gains {p: 100, d: 80, i: 10, i_clamp: 1.5}
    arm_right_6_joint: &arm_6_gains {p: 100, d: 80, i: 10, i_clamp: 1.5}
    arm_right_7_joint: &arm_7_gains {p: 100, d: 80, i: 10, i_clamp: 1.5}
    arm_left_1_joint:  *arm_1_gains
    arm_left_2_joint:  *arm_2_gains
    arm_left_3_joint:  *arm_3_gains
    arm_left_4_joint:  *arm_4_gains
    arm_left_5_joint:  *arm_5_gains
    arm_left_6_joint:  *arm_6_gains
    arm_left_7_joint:  *arm_7_gains
