head_traj_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &head_joints
    - head_1_joint
    - head_2_joint
  gains:
    head_1_joint: {p: 300, d: 250, i: 10, i_clamp: 1.5}
    head_2_joint: {p: 300, d: 250, i: 10, i_clamp: 1.5}
  joint_trajectory_action_node:
    joints: *head_joints
    constraints:
      goal_time: 0.6
      head_1_joint:
        goal: 0.02
      head_2_joint:
        goal: 0.02
