right_hand_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &hand_right_joints
    - hand_right_thumb_joint
    - hand_right_index_1_joint
    - hand_right_index_2_joint
    - hand_right_index_3_joint
    - hand_right_middle_1_joint
    - hand_right_middle_2_joint
    - hand_right_middle_3_joint

  gains:
    hand_right_thumb_joint:    &thumb_gains    {p: 100, d: 80, i: 10, i_clamp: 1.5}
    hand_right_index_1_joint:  &finger_1_gains {p: 100, d: 80, i: 10, i_clamp: 1.5}
    hand_right_index_2_joint:  &finger_2_gains {p: 100, d: 80, i: 10, i_clamp: 1.5}
    hand_right_index_3_joint:  &finger_3_gains {p: 100, d: 80, i: 10, i_clamp: 1.5}
    hand_right_middle_1_joint: *finger_1_gains
    hand_right_middle_2_joint: *finger_2_gains
    hand_right_middle_3_joint: *finger_3_gains
  joint_trajectory_action_node:
    joints: *hand_right_joints
    constraints: 
      goal_time: &goal_time_constraint 0.6
      hand_right_thumb_joint:
        goal: &goal_pos_constraint 0.02
      hand_right_index_1_joint:
        goal: *goal_pos_constraint
      hand_right_middle_1_joint:
        goal: *goal_pos_constraint

left_hand_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &hand_left_joints
    - hand_left_thumb_joint
    - hand_left_index_1_joint
    - hand_left_index_2_joint
    - hand_left_index_3_joint
    - hand_left_middle_1_joint
    - hand_left_middle_2_joint
    - hand_left_middle_3_joint

  gains:
    hand_left_thumb_joint:    *thumb_gains
    hand_left_index_1_joint:  *finger_1_gains
    hand_left_index_2_joint:  *finger_2_gains
    hand_left_index_3_joint:  *finger_3_gains
    hand_left_middle_1_joint: *finger_1_gains
    hand_left_middle_2_joint: *finger_2_gains
    hand_left_middle_3_joint: *finger_3_gains
  joint_trajectory_action_node:
    joints: *hand_left_joints
    constraints: 
      goal_time: *goal_time_constraint
      hand_left_thumb_joint:
        goal: *goal_pos_constraint
      hand_left_index_1_joint:
        goal: *goal_pos_constraint
      hand_left_middle_1_joint:
        goal: *goal_pos_constraint

