both_arms_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints:
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  gains:
    arm_right_1_joint: {p: 800.0, d: 500.0}
    arm_right_2_joint: {p: 800.0, d: 500.0}
    arm_right_3_joint: {p: 600.0, d: 400.0}
    arm_right_4_joint: {p: 800.0, d: 600.0}
    arm_right_5_joint: {p: 200.0, d: 140.0}
    arm_right_6_joint: {p: 200.0, d: 140.0}
    arm_right_7_joint: {p: 200.0, d: 160.0}
    arm_left_1_joint:  {p: 800.0, d: 500.0}
    arm_left_2_joint:  {p: 800.0, d: 500.0}
    arm_left_3_joint:  {p: 600.0, d: 400.0}
    arm_left_4_joint:  {p: 800.0, d: 600.0}
    arm_left_5_joint:  {p: 200.0, d: 140.0}
    arm_left_6_joint:  {p: 200.0, d: 140.0}
    arm_left_7_joint:  {p: 200.0, d: 160.0}
  joint_trajectory_action_node:
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
    constraints:
      goal_time: 0.6
      arm_right_1_joint:
        goal: 0.02
      arm_right_2_joint:
        goal: 0.02
      arm_right_3_joint:
        goal: 0.02
      arm_right_4_joint:
        goal: 0.02
      arm_right_5_joint:
        goal: 0.02
      arm_right_6_joint:
        goal: 0.02
      arm_right_7_joint:
        goal: 0.02
      arm_left_1_joint:
        goal: 0.02
      arm_left_2_joint:
        goal: 0.02
      arm_left_3_joint:
        goal: 0.02
      arm_left_4_joint:
        goal: 0.02
      arm_left_5_joint:
        goal: 0.02
      arm_left_6_joint:
        goal: 0.02
      arm_left_7_joint:
        goal: 0.02